### ISSUE TITLE
Save As dialog creates empty files, asks to overwrite

### ISSUE THREAD

**Issue by jpgaribotti** [google/google-drive-shell-extension#12]
Repro steps:
- Create new file from within an application. 
- Select Save as from windows menu and then select Drive.
- When saving, an empty file is created of the same name as the "Save As" filename. In Citrix environments, this is repeated for each and every folder you navigate to. 
- You are then warned that a file already exists and are asked to overwrite the destination.

**Comment by pshorney** [comment]
Confirmed see same results i.e. multiple files in Word and Powerpoint

**Comment by jpgaribotti** [comment]
Small regression introduced with the pull request: Overwriting existing files fails with "The system cannot find the path specified."

As we no longer create dummy files when checking if a path exists, "existing" files that haven't been downloaded don't actually yet exist, and so can't be overwritten.
