### ISSUE TITLE
Deleting a directory restarts explorer.exe

### ISSUE THREAD

**Issue by fthdgn** [google/google-drive-shell-extension#21]
When I tried to delete a directory from Google Drive Shell Extension drive, explorer.exe restarts.

Operating system: Windows 10 64-bit

Crash log: https://gist.github.com/fthdgn/9714b740b85ea6fc86f9

**Comment by jpgaribotti** [comment]
What version of the extension were you running? v1.8.55.0 fixed a case where that was happening.

**Comment by fthdgn** [comment]
Sorry, I forgot to say version. It is v1.8.55.1. I have downloaded it from releases today.

**Comment by jpgaribotti** [comment]
Thank you for the report, will look into it.

**Comment by pizixie** [comment]
i have this problem yet.
it show a "Miss File Dialog" when delete a directory.
the version is 1.8.57.0.
@jpgaribotti 

oh,the OS is windows server 2008 R2
